#@TYPE: Machine
#@Name: MICROCHIP SAM9X75EB NAND
#@DESCRIPTION: Machine configuration for Microchip SAM9X75 NAND evaluation board

require include/sam9x75.inc

KERNEL_DEVICETREE = "microchip/at91-sam9x75eb.dtb"
DT_MACHINE ?= "sam9x75eb"

IMAGE_FSTYPES += " ubi tar.gz"

MACHINE_ESSENTIAL_EXTRA_RDEPENDS += " dt-overlay-mchp"

# Add deploy functions to the wic image dependency
do_image_wic[depends] += " u-boot-mchp:do_deploy"
do_image_wic[depends] += " dt-overlay-mchp:do_deploy"

# NAND
MKUBIFS_ARGS = " -e 0x3e000 -c 2082 -m 0x1000 -x lzo"
UBINIZE_ARGS = " -m 0x1000 -p 0x40000"
MKENVIMAGE_EXTRA_ARGS = " -r "

UBI_VOLNAME = "rootfs"

UBOOT_MACHINE ?= "sam9x75eb_nandflash_defconfig"
UBOOT_ENTRYPOINT = "0x20008000"
UBOOT_LOADADDRESS = "0x20008000"
UBOOT_ENV_SIZE = "0x20000"

MACHINEOVERRIDES =. "mpuall:sam9x75eb:"
