#@TYPE: Machine
#@Name: MICROCHIP SAM7D65-CURIOSITY NAND
#@DESCRIPTION: Machine configuration for Microchip SAM9X75 curiosity nand board

require include/sama7d65.inc

KERNEL_DEVICETREE = "microchip/at91-sama7d65_curiosity.dtb"
DT_MACHINE ?= "sama7d65_curiosity"

IMAGE_FSTYPES += " ubi tar.gz"

MACHINE_ESSENTIAL_EXTRA_RDEPENDS += " dt-overlay-mchp"

# Add deploy functions to the wic image dependency
do_image_wic[depends] += " u-boot-mchp:do_deploy"
do_image_wic[depends] += " dt-overlay-mchp:do_deploy"

# NAND
MKUBIFS_ARGS = " -e 0x3e000 -c 2082 -m 0x1000 -x lzo"
UBINIZE_ARGS = " -m 0x1000 -p 0x40000"
MKENVIMAGE_EXTRA_ARGS = " -r "

UBI_VOLNAME = "rootfs"

UBOOT_MACHINE ?= "sama7d65_curiosity_nandflash_defconfig"
UBOOT_ENTRYPOINT = "0x62000000"
UBOOT_LOADADDRESS = "0x62000000"
UBOOT_ENV_SIZE = "0x4000"

MACHINEOVERRIDES =. "mpuall:sama7d65:"
