#@TYPE: Machine
#@Name: Microchip SAMA7G5-EK oSPI
#@DESCRIPTION: Machine configuration for Microchip SAMA7G5 ospi evaluation kit

require include/sama7g5.inc

MACHINE_FEATURES = "apm ubi usbhost usbgadget"
KERNEL_DEVICETREE = "microchip/at91-sama7g5ek.dtb"
DT_MACHINE ?= "sama7g5ek"

IMAGE_FSTYPES += "ubi tar.gz"

IMAGE_ROOTFS_SIZE = "122880"
IMAGE_ROOTFS_MAXSIZE = "122880"
MKUBIFS_ARGS = " -e 0xff80 -c 1924 -m 1"
UBINIZE_ARGS = " -m 1 -p 0x10000 -O 64 -s 1"

UBI_VOLNAME = "rootfs"

UBOOT_MACHINE ?= "sama7g5ek_qspi0_defconfig"
UBOOT_ENTRYPOINT = "0x62000000"
UBOOT_LOADADDRESS = "0x62000000"
UBOOT_ENV_SIZE = "0x4000"

MACHINEOVERRIDES =. "mpuall:sama7g5ek:"

# OSPI image must fit into 120 MBytes
IMAGE_INSTALL:forcevariable = "\
    can-utils \
    dosfstools \
    devmem2 \
    evtest \
    fswebcam \
    gstreamer1.0-plugins-base \
    i2c-tools \
    kernel-modules \
    libgpiod-tools \
    libv4l \
    linuxptp \
    lmbench \
    ltrace \
    media-ctl \
    mtd-utils \
    mtd-utils-ubifs \
    packagegroup-base-wifi \
    packagegroup-base-usbgadget \
    packagegroup-core-boot \
    phytool \
    rng-tools \
    setserial \
    strace \
    stress-ng \
    systemd-analyze \
    usbutils \
    video-capture-at91\
    v4l-utils \
    wget \
"
IMAGE_FEATURES:remove = "package-management"

MACHINE_ESSENTIAL_EXTRA_RDEPENDS += " dt-overlay-mchp"

# Add deploy functions to the wic image dependency
do_image_wic[depends] += " u-boot-mchp:do_deploy"
do_image_wic[depends] += " dt-overlay-mchp:do_deploy"
