#@TYPE: Machine
#@Name: MICROCHIP SAMA5D3 Xplained
#@DESCRIPTION: Machine configuration for Microchip SAMA5D3 Xplained nand board

require include/sama5d3.inc

MACHINE_FEATURES += " wifi"
KERNEL_DEVICETREE = "microchip/at91-sama5d3_xplained.dtb"
DT_MACHINE ?= "sama5d3_xplained"

# used by sysvinit_2
SERIAL_CONSOLES ?= "115200;ttyS0 115200;ttyGS0"

IMAGE_FSTYPES += " ubi tar.gz"

MACHINE_ESSENTIAL_EXTRA_RDEPENDS += " dt-overlay-mchp"

# Add deploy functions to the wic image dependency
do_image_wic[depends] += " u-boot-mchp:do_deploy"
do_image_wic[depends] += " dt-overlay-mchp:do_deploy"

# NAND
MKUBIFS_ARGS ?= " -e 0x1f000 -c 2048 -m 0x800  -x lzo"
UBINIZE_ARGS ?= " -m 0x800 -p 0x20000 -s 2048"
MKENVIMAGE_EXTRA_ARGS = " -r "

UBI_VOLNAME = "rootfs"

UBOOT_MACHINE ?= "sama5d3_xplained_nandflash_config"
UBOOT_ENTRYPOINT = "0x20008000"
UBOOT_LOADADDRESS = "0x20008000"
UBOOT_ENV_SIZE = "0x20000"

MACHINEOVERRIDES =. "mpuall:sama5d3_xplained:"
