#@TYPE: Machine
#@Name: MICROCHIP SAMA5D2 Xplained SPIFLASH
#@DESCRIPTION: Machine configuration for Microchip SAMA5D2 Xplained spiflash board

require include/sama5d2.inc

KERNEL_DEVICETREE = "microchip/at91-sama5d2_xplained.dtb"
DT_MACHINE ?= "sama5d2_xplained"

IMAGE_FSTYPES += " tar.gz wic"

WKS_FILE = "sdimage.wks"

MACHINE_ESSENTIAL_EXTRA_RDEPENDS += " dt-overlay-mchp"

# Add deploy functions to the wic image dependency
do_image_wic[depends] += " u-boot-mchp:do_deploy"
do_image_wic[depends] += " dt-overlay-mchp:do_deploy"

# Install kernel and dtbs in rootfs that is on eMMC
IMAGE_INSTALL:append = " kernel-image kernel-devicetree"

UBOOT_MACHINE ?= "sama5d2_xplained_spiflash_defconfig"
UBOOT_ENTRYPOINT = "0x20008000"
UBOOT_LOADADDRESS = "0x20008000"
UBOOT_ENV_SIZE = "0x20000"

MACHINEOVERRIDES =. "mpuall:sama5d2_xplained:"
