#@TYPE: Machine
#@Name: Microchip SAMA7D65-CURIOSITY-PRO SD
#@DESCRIPTION: Machine configuration for Microchip SAMA7D65 curiosity pro sd board

require include/sama7d65.inc

MACHINE_FEATURES = "apm alsa ext2 ext3 usbhost usbgadget"
KERNEL_DEVICETREE = "microchip/at91-sama7d65_curiosity_pro.dtb"
DT_MACHINE ?= "sama7d65_curiosity_pro"

IMAGE_FSTYPES += " tar.gz wic"

WKS_FILE = "sdimage-bootpart.wks"
IMAGE_BOOT_FILES = "BOOT.BIN u-boot.bin uboot.env sama7d65_curiosity_pro.itb"

UBOOT_MACHINE ?= "sama7d65_curiosity_pro_mmc1_defconfig"
UBOOT_ENTRYPOINT = "0x62000000"
UBOOT_LOADADDRESS = "0x62000000"
UBOOT_ENV_SIZE = "0x4000"

MACHINE_ESSENTIAL_EXTRA_RDEPENDS += " dt-overlay-mchp"

# Add deploy functions to the wic image dependency
do_image_wic[depends] += " u-boot-mchp:do_deploy"
do_image_wic[depends] += " dt-overlay-mchp:do_deploy"

MACHINEOVERRIDES =. "mpuall:sama7d65:"
