#@TYPE: Machine
#@Name: MICROCHIP SAMA5D4 Xplained Ultra NAND
#@DESCRIPTION: Machine configuration for Microchip SAMA5D4 xplained nand board

require include/sama5d4.inc

KERNEL_DEVICETREE = "microchip/at91-sama5d4_xplained.dtb"
DT_MACHINE ?= "sama5d4_xplained"

IMAGE_FSTYPES += " ubi tar.gz"

MACHINE_ESSENTIAL_EXTRA_RDEPENDS += " dt-overlay-mchp"

# Add deploy functions to the wic image dependency
do_image_wic[depends] += " u-boot-mchp:do_deploy"
do_image_wic[depends] += " dt-overlay-mchp:do_deploy"

# NAND
MKUBIFS_ARGS = " -e 0x3e000 -c 2082 -m 0x1000 -x lzo"
UBINIZE_ARGS = " -m 0x1000 -p 0x40000"
MKENVIMAGE_EXTRA_ARGS = " -r "

UBI_VOLNAME = "rootfs"

UBOOT_MACHINE ?= "sama5d4_xplained_nandflash_config"
UBOOT_ENTRYPOINT = "0x20008000"
UBOOT_LOADADDRESS = "0x20008000"
UBOOT_ENV_SIZE = "0x20000"

MACHINEOVERRIDES =. "mpuall:sama5d4_xplained:"
