DISTRO = "mchp-distro"
DISTRO_NAME = "Microchip Distro"
DISTRO_VERSION = "1.0"

DISTROOVERRIDES = "${DISTRO}"
TARGET_VENDOR = "-mchp"
SDK_VENDOR = "-mchpsdk"

MAINTAINER = "\
		Valentina Fernandez <valentina.fernandezalanis@microchip.com> \
		Nicolas Ferre <nicolas.ferre@microchip.com> \
		Dharma Balasubiramani <dharma.b@microchip.com> \
		"

MCHP_INIT_MANAGER ?= "systemd"
PACKAGE_CLASSES ?= "package_ipk"

MCHP_DEFAULT_DISTRO_FEATURES = ""
DISTRO_FEATURES ?= "${DISTRO_FEATURES_DEFAULT} ${MCHP_DEFAULT_DISTRO_FEATURES}"

PACKAGE_CLASSES ?= "package_ipk"

INIT_MANAGER ?= "${MCHP_INIT_MANAGER}"
