# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-mchp-mpu-apps"
BBFILE_PATTERN_meta-mchp-mpu-apps = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-mchp-mpu-apps = "6"

LICENSE_PATH += "${LAYERDIR}/licenses"

SIGGEN_EXCLUDE_SAFE_RECIPE_DEPS += " \
    mchp-egt-demo-init->udev-rules-mchp \
    noto-fonts->fontconfig \
"
LAYERDEPENDS_meta-mchp-mpu-apps = "meta-mchp-mpu-bsp openembedded-layer"
LAYERSERIES_COMPAT_meta-mchp-mpu-apps = "scarthgap styhead"
