#!/bin/sh

start()
{
    . /etc/profile

    WESTON_INI=/etc/weston.ini

    res=$(cat /sys/class/drm/card0/*/modes | tr -d '\n')
    case "$res" in
     "480x272")
         WESTON_INI=/etc/weston-wqvga.ini
         ;;
    esac

	weston-start -- --tty=3 -B drm-backend.so -c $WESTON_INI --idle-time=0 --use-pixman
}

stop()
{
	echo "Stopping Weston"
	killproc weston
}


case "$1" in
  start)
    start
  ;;
  stop)
    stop
  ;;
  *)
  ;;
esac
