#@TYPE: Machine
#@NAME: mpfs-icicle-kit-prod-auth
#@SOC: Polarfire SoC
#@DESCRIPTION: Machine configuration for the Microchip Polarfire SoC Icicle Kit with authenticated boot

require include/mpfs-common.inc

MACHINE_TYPE = "smp"

MACHINE_FEATURES:append = " pci usbgadget usbhost wifi"

RISCV_SBI_FDT ?=  "mpfs-icicle-kit-prod.dtb"
KERNEL_DTC_FLAGS += "-@"
KERNEL_DEVICETREE ?= "microchip/${RISCV_SBI_FDT}"

UBOOT_MACHINE = "microchip_mpfs_icicle_defconfig"

HSS_PAYLOAD = "uboot"

UBOOT_SIGN_ENABLE = "1"
UBOOT_SIGN_KEYNAME ?= "mpfs_fitimage_key"
UBOOT_SIGN_KEYDIR ?= "${TOPDIR}/../keys"
UBOOT_MKIMAGE_DTCOPTS = "-I dts -O dtb -p 2000"

FIT_SIGN_ALG = "rsa4096"
FIT_HASH_ALG = "sha256"

HSS_PAYLOAD_PRIVATE_KEYNAME ?= "x509-ec-secp384r1-private"
HSS_PAYLOAD_KEYDIR ?= "${TOPDIR}/../keys"

INITRAMFS_IMAGE = "mchp-initramfs-image"

IMAGE_BOOT_FILES ?= " \
    fitImage \
"

WKS_FILE ?= "mpfs-rootfs.wks"

MACHINEOVERRIDES .= ":mpfs:mpfs-icicle-kit-all::mpfs-icicle-kit-auth"
